version: "2"
services:
  node-app:
    container_name: node-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"